name: IA Size Calculator

on:
  workflow_dispatch:
    inputs:
      search_query:
        description: 'Search Query (e.g., uploader:jscott@archive.org)'
        required: true
        default: 'uploader:example@example.com'

jobs:
  calculate-size:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-calc-${{ hashFiles('.github/workflows/acc_calc.yml') }}
          restore-keys: |
            ${{ runner.os }}-calc-

      - name: Install Dependencies
        run: |
          pip install internetarchive

      - name: Run Calculation
        env:
          INPUT_QUERY: ${{ inputs.search_query }}
        run: python ia_calculator.py